apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swapp-ingress
  namespace: mixed-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: simple-web-app-service
            port: 
              number: 8080
        path: /mixedDemo/?(.*)
        pathType: Prefix
