apiVersion: v1
kind: Service
metadata:
  name: simpleWebAppService
  namespace: web-app-demo
  labels:
    app: simpleWebApp
spec:
  selector:
    app: simpleWebApp
  ports: 
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
